name: amazon_clone_admin
description: A Flutter web admin panel for an Amazon clone application
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.20.2
  http: ^1.3.0
  shared_preferences: ^2.2.0
  shared_preferences_web: ^2.1.1+1
  flutter_hooks: ^0.21.2
  syncfusion_flutter_datagrid: ^29.1.33
  fl_chart: ^0.70.2
  percent_indicator: ^4.0.1
  flutter_vector_icons: ^2.0.0
  logger: ^2.5.0
  fluttertoast: ^8.2.2
  get_it: ^8.0.3
  equatable: ^2.0.5
  meta: ^1.8.0
  collection: ^1.17.0
  path_provider: ^2.1.1
  universal_html: ^2.2.1
  js: ^0.7.2
  json_annotation: ^4.9.0
  haptic_feedback: ^0.5.1+1
  syncfusion_flutter_charts: ^29.1.40
  flutter_typeahead: ^5.2.0
  hooks_riverpod: ^2.6.1
  pull_to_refresh: ^2.0.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.1
  mockito: ^5.4.0
  test: ^1.24.6
  lint: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
